### ISSUE TITLE
 mtm6201_010_ final - questions and struggles 

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201_final#1]
@abhaysharma
I have used Bootstrap to create the navbar for the mobile version, but I'm unsure how to create a responsive navbar (how to make the desktop version). I'm returning to the media star code in-class notes for reference, but I keep getting stuck. How do I change the colour of the nav bar to a customer background colour? Also, I am using the Bootstrap template and trying to change as much as possible; however, I am confused about what to change.  Lines 22 to 45 Bootstrap has an off-canvas reference in the classes; I am unsure if I need to change the classes.
How do I create a responsive image with Bootstrap? I tried creating an HTML responsive image; however, it was not responsive. The desktop responsive image is not working. I am struggling with the font styles, types, and font sizes with the Bootstrap code. How do you warp the font following the line? 

@coop0162

**Comment by abhaysharma** [comment]
@coop0162 

For your navigation, you will need to remove the existing navigation and replace it with the first navbar example code from Bootstrap.

The font used in the design is "Epilogue", you can look it up on Google Fonts or use a similar font.

To fix the layout for the banner you will need the following syntax with a bootstrap grid
```
<section class="container-fluid banner bg-dark">
  <div class="container-xl">
    <div class="row">
      <div class="col-md order-md-1">
      </div>
      <div class="col-md">
      </div>
    </div>
  </div>
</section><!--close container-fluid all the dark blue bg-->
```
