### ISSUE TITLE
mtm6201_010_ final- questions

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201_final#2]
@abhaysharma

I have find the epilogue font however not working properly. It is a Google Font. I may have place the embed incorrectly in the html or css.
[Google Font Epilogue](https://fonts.google.com/specimen/Epilogue)
[Google Font Epilque Embed code] (https://fonts.google.com/selection/embed)

**Comment by abhaysharma** [comment]
@coop0162 you need to first copy the embed link into the head of your HTML document, this step is done. 
Then in your CSS, you need to select the element in this case body tag to assign the font-family.
body{
font-family: "Epilogue", sans-serif;
}
