### ISSUE TITLE
mtm6201_010_ final- questions

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201_final#3]
@abhaysharma

I have structured HTML code and now Bootstrap.  I have difficulties with bootstrap card formate which one to choose? line 129 to 149 ( static of company and facts of company formate ). It it one row and three colunms.

**Comment by abhaysharma** [comment]
@coop0162 the issue is that you are missing the closing div tags for your .col-md divs. Lines 135 has a comment but no closing div.
