### ISSUE TITLE
mtm6201_010_ final - icons ( email address and section)

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201_final#6]
@abhaysharma

Alignment of the icon beside the phone, email, and address section at the bottom of the website. line 290 and 309.
I had trouble downloading the whole contact icon image ( phone, email, and address) on Adobe XD. Adobe XD downloads the icon separately -background ( oval) and icon. In CSS, I place the oval icon as a background and place the contact icon in HTML.

**Comment by abhaysharma** [comment]
@coop0162 you can use a font icon instead of the images for the icons for the contact section. You can also use bootstrap icons, as practiced for three-star media example.
